### ISSUE TITLE
Only Who is info is shown

### ISSUE THREAD

**Issue by ravdeepsingh22** [ppshobi/tech-detector#1]
The app demo shows just who is info and ip details 
No backend Technologies , frameworks, and other technologies used. are Shown in Demo

**Comment by ppshobi** [comment]
Infact I have noticed this thing. Sometimes it detects the technologies but
some times it doesn't. Its a node Js module which is responsible for
detecting the technologies
 I will try to fix it

**Comment by tier5** [comment]
wappalyzer has changed there code
